### PR TITLE
docs: fix typo in README.md

### PR DESCRIPTION
**Pull request by pgrimaud**
Hi,

This tiny PR will fix : 

- 1 typo in `README.md`

Cheers! :robot:

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@pgrimaud thanks for taking the time to fix this typo. 🙌

**Comment by nelsonic** [comment]
P.S. How did you _discover_ this repo? 💭

**Comment by pgrimaud** [comment]
I found this one on Google : https://github.com/dwyl/learn-devops
Then I navigated to this organization and opened various interesting repos.


@dwyl team make an awesome job with tuts and examples. All I love 🤩

**Comment by nelsonic** [comment]
@pgrimaud thanks for letting us know. ☀️

**Pull request merged**
